MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from formapp import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('formapp.urls')),
    path('', include('django.contrib.auth.urls')),
    path('settings/', views.settings, name='settings'),
    path('oauth/', include('social_django.urls', namespace='social')),
    # path('settings/password/', views.password, name='password'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

formapp/urls.py
from django.urls import path, include
from . import views
# from django.contrib.auth.urls import views as auth_views

app_name = 'formapp'

urlpatterns = [
    path('', views.Information, name='info'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('delete/(int:<id>)', views.delete, name='employee_delete'),
    path('update/<int:id>/', views.UpdateView, name='update'),
    path('password/<int:id>',
         views.password_change_view, name='change_password'),
    path('html_to_pdf_view/<int:id>',
         views.html_to_pdf_view, name="html_to_pdf_view"),
    path('csv_view/(<int:id>)', views.csv_view, name='csv_view'),
    path('show', views.show, name="show"),
    # path('edit/(<int:id>)', views.edit, name='employee_edit'),
    path('view_profile/(<int:id>)',
         views.view_profile, name="view_profile"),




    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

formapp/models.py
from django.db import models
from django.contrib.auth.models import User

OPTIONS = (
    ("C++", "C++"),
    ("JAVA", "Core JAVA"),
    ("Python", "Advanced Python Django"),
    ("C Sharp", "C Sharp"),
    ("ASP.net", "ASP.net"),
    ("Magento", "Magento"),
    ("Swift", "Swift"),
    ("HTML CSS", "HTML CSS"),
    ("Networking", "Networking"),
)

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)


count = (
    ("India", "India"),
    ("Other", "Other")
)


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gender = models.CharField(
        max_length=2,
        choices=GENDER_CHOICES,
    )
    Address = models.CharField(max_length=1024)
    Mobile_No = models.CharField(max_length=11)
    Date_of_Birth = models.DateField(null=True)
    Programming_Languages = models.CharField(max_length=1000, choices=OPTIONS)
    Country = models.CharField(choices=count, max_length=1000)
    Image = models.ImageField(upload_to='profile_pics')
    File = models.FileField(upload_to='get_file', null=True, blank=True)

    def __str__(self):
        return self.user.username


# Create your models here.

formapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Employee, OPTIONS, GENDER_CHOICES, count


class RegisterForm(forms.ModelForm):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    Address = forms.CharField(max_length=1024)
    Mobile_No = forms.CharField(max_length=11)
    Programming_Languages = forms.MultipleChoiceField(
        choices=OPTIONS, widget=forms.CheckboxSelectMultiple)
    Date_of_Birth = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}))
    Country = forms.ChoiceField(choices=count, widget=forms.RadioSelect)
    Image = forms.ImageField(required=False)
    File = forms.FileField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'gender', 'Address',
                  'Date_of_Birth', 'Mobile_No', 'password', 'password_confirm', 'Programming_Languages', 'Country', 'Image', 'File']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('.com'):
            raise forms.ValidationError("Only .com email addresses allowed")
        return email

    def clean_Mobile_No(self):
        Mobile_No = self.cleaned_data.get('Mobile_No')
        if len(Mobile_No) < 9:
            raise forms.ValidationError(
                "This is India! Enter a 10 digit number!!!")
        return Mobile_No

    def clean_Date_of_Birth(self):
        Date_of_Birth = self.cleaned_data.get("Date_of_Birth")
        if not '%m-%d-%Y':
            raise forms.ValidationError(
                "value has an invalid date format. It must be in YYYY-MM-DD format.")
        return Date_of_Birth

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password_confirm:
            raise forms.ValidationError("You must confirm your password")
        if password != password_confirm:
            raise forms.ValidationError("Your passwords do not match")
        return cleaned_data


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class UpdateForm(forms.ModelForm):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    Address = forms.CharField(max_length=1024)
    Mobile_No = forms.CharField(max_length=11)
    Programming_Languages = forms.MultipleChoiceField(
        choices=OPTIONS, widget=forms.CheckboxSelectMultiple)
    Date_of_Birth = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    count = (
        ("india", "India"),
        ("out", "other")
    )
    Country = forms.ChoiceField(choices=count, widget=forms.RadioSelect)

    class Meta:
        model = User
        fields = ['email', 'gender', 'Address',
                  'Date_of_Birth', 'Mobile_No', 'Programming_Languages', 'Country']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('.com'):
            raise forms.ValidationError("Only .com email addresses allowed")
        return email

    def clean_Mobile_No(self):
        Mobile_No = self.cleaned_data.get('Mobile_No')
        if len(Mobile_No) < 9:
            raise forms.ValidationError(
                "This is India! Enter a 10 digit number!!!")
        return Mobile_No

    def clean_Date_of_Birth(self):
        Date_of_Birth = self.cleaned_data.get("Date_of_Birth")
        if not '%m-%d-%Y':
            raise forms.ValidationError(
                "value has an invalid date format. It must be in YYYY-MM-DD format.")
        return Date_of_Birth


class PasswordResetForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['password', 'password_confirm']

    def clean(self):
        cleaned_data = super(PasswordResetForm, self).clean()
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password_confirm:
            raise forms.ValidationError("You must confirm your password")
        if password != password_confirm:
            raise forms.ValidationError("Your passwords do not match")
        return cleaned_data

formapp/views.py
import os
import csv
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login as u_login, logout as u_logout
from django.template.loader import get_template
from django.template import Context
from django.conf import settings as conf_settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.contrib.auth.forms import (
    PasswordChangeForm,
    AdminPasswordChangeForm)
from django.contrib import messages
from social_django.models import UserSocialAuth
from xhtml2pdf import pisa
from io import StringIO
from .forms import RegisterForm, UpdateForm, PasswordResetForm
from .models import Employee


def Information(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            object = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            object.set_password(password)
            object.save()
            profile = Employee()
            profile.user = object
            profile.Mobile_No = form.cleaned_data["Mobile_No"]
            profile.gender = form.cleaned_data["gender"]
            profile.Date_of_Birth = form.cleaned_data["Date_of_Birth"]
            profile.Address = form.cleaned_data["Address"]
            profile.Programming_Languages = form.cleaned_data["Programming_Languages"]
            profile.Country = form.cleaned_data["Country"]
            profile.Image = form.cleaned_data["Image"]
            if not profile.Image:
                profile.Image = 'media/default.jpg'
            profile.File = form.cleaned_data["File"]
            profile.save()
            messages.success(
                request, 'Your account has been created! You are now able to login')
            return HttpResponseRedirect('login')
    else:
        form = RegisterForm()
    return render(request, 'formapp/register.html', {'form': form})


def show(request):
    # employees = Employee.objects.all()
    employees = Employee.objects.order_by("-id").all()
    paginator = Paginator(employees, 6)

    page = request.GET.get('page')
    try:
        employees = paginator.page(page)
    except PageNotAnInteger:
        employees = paginator.page(1)
    except EmptyPage:
        employees = paginator.page(paginator.num_pages)
    return render(request, "formapp/show.html", {'employees': employees})


def view_profile(request, id):
    if id:
        employee = Employee.objects.get(user_id=id)
    else:
        employee = request.employee
    args = {'employee': employee}
    return render(request, 'formapp/home.html', args)


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            if user.is_active and user.is_superuser:
                u_login(request, user)
                if request.GET.get('next', None):
                    return redirect(request.GET.get['next'])
                return redirect('formapp:show')
            else:
                if user.is_active:
                    u_login(request, user)
                return redirect('formapp:home')
        else:
            return redirect('password_reset')
    else:
        return render(request, 'formapp/login.html', {})


def home(request):
    print(request.user)
    employee = Employee.objects.get(user_id=request.user.id)
    return render(request, 'formapp/home.html', {'employee': employee})


def logout(request):
    u_logout(request)
    return redirect('login')


def UpdateView(request, id):
    employee = get_object_or_404(Employee, user_id=request.user.id)
    data = {}
    data['email'] = employee.user.email
    data['gender'] = employee.gender
    data['Address'] = employee.Address
    data['Mobile_No'] = employee.Mobile_No
    data['Date_of_Birth'] = employee.Date_of_Birth
    data['Programming_Languages'] = employee.Programming_Languages
    data['Country'] = employee.Country

    if request.method == 'POST':
        form = UpdateForm(request.POST)
        if form.is_valid():
            employee.email = request.POST.get('email')
            employee.gender = request.POST.get('gender')
            employee.Address = request.POST.get('Address')
            employee.Mobile_No = request.POST.get('Mobile_No')
            employee.Date_of_Birth = request.POST.get('Date_of_Birth')
            employee.Programming_Languages = request.POST.get(
                'Programming_Languages')
            employee.Country = request.POST.get('Country')
            employee.save()
        return redirect('formapp:home')
    else:
        form = UpdateForm(initial=data)
    return render(request, 'formapp/update.html', {'form': form})


def delete(request, id):
    employee = get_object_or_404(User, id=id)
    employee.delete()
    return redirect('formapp:info')


def password_change_view(request, id):
    employee = get_object_or_404(User, id=id)
    data = {}
    data['password'] = employee.password
    if request.method == 'POST':
        form = PasswordResetForm(request.POST, instance=employee)
        if form.is_valid():
            object = form.save(commit=False)
            password = form.cleaned_data['password']
            object.set_password(password)
            object.save()
            # password = request.POST.get('password')
            # employee.set_password(password)
            # employee.save()
        return redirect('login')
        # return HttpResponse('home')
    else:
        form = PasswordResetForm(initial=data)
    return render(request, 'formapp/change_password.html', {'form': form})


def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
        employee, created = Employee.objects.get_or_create(
            user=github_login.user
        )
        print(employee.user_id)
    except UserSocialAuth.DoesNotExist:
        github_login = None

    can_disconnect = (user.social_auth.count() >
                      1 or user.has_usable_password())

    return render(request, 'formapp/settings.html', {
        'github_login': github_login,
        'can_disconnect': can_disconnect,
        'employee': employee
    })


def html_to_pdf_view(request, id):
    employee = Employee.objects.get(user_id=id)
    template_path = 'formapp/pdf.html'
    context = {'pagesize': 'A4',
               'employee': employee,
               }    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisaStatus = pisa.CreatePDF(
        html, dest=response, link_callback=link_callback)
    # if error then show some funy view
    if pisaStatus.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def link_callback(uri, rel):
    path = os.path.join(conf_settings.MEDIA_ROOT,
                        uri.replace(conf_settings.MEDIA_URL, ""))
    return path


def csv_view(request, id):
    employee = Employee.objects.get(user_id=id)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', employee.user.username])
    writer.writerow(['email', employee.user.email])
    writer.writerow(['Mobile_No', employee.Mobile_No])
    writer.writerow(['Date_of_Birth', employee.Date_of_Birth])
    writer.writerow(['Gender', employee.gender])
    writer.writerow(['Address', employee.Address])
    writer.writerow(['Country', employee.Country])
    writer.writerow(['Programming_Languages', employee.Programming_Languages])
    return response

formapp/templates/formapp/change_password.html
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

formapp/templates/formapp/home.html
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 1px 0 0 1px;
    }
</style>
</head>
<html lang="en" dir="ltr">
{% csrf_token %}
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>

  <body>
    <br>
    <img class="rounded-circle account-img" img src="{{ employee.Image.url }}" width="200">
    <br><br>
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info :</legend>
    </fieldset>
    <h3>Welcome {{ employee.user.username }}</h3>
    <p>Email: {{ employee.user.email }}</p>
    <p>Gender: {{ employee.gender }}</p>
    <p>Address: {{ employee.Address }}</p>
    <p>Country: {{ employee.Country }}</p>
    <p>Programming_Languages: {{ employee.Programming_Languages }}</p>
    <p>Date_of_Birth: {{ employee.Date_of_Birth}}</p>
    <p>Mobile_No.: {{ employee.Mobile_No}}</p>
    <p>File: <a href="{{ employee.File.url }}" class="btn btn-info" target="_blank">Download File</a></p>

    <a href="{% url 'logout' %}" class="btn btn-info">Logout</a>
    <a href="{% url 'formapp:update' employee.user_id  %}" class="btn btn-info">Update</a>
    <a href="{% url 'formapp:change_password' employee.user_id  %}" class="btn btn-info">Change Password</a>
    <a href="{% url 'formapp:employee_delete' employee.user_id  %}" class="btn btn-info"  style="background-color:#f44336" >Delete</a>
    <a href="{% url 'formapp:html_to_pdf_view' employee.user_id %}" class="btn btn-info">Print</a>
    <a href="{% url 'formapp:csv_view' id=employee.user_id %}" class="btn btn-primary">csv file</a> <br><br>


  </body>
</html>

formapp/templates/formapp/login.html
{% load widget_tweaks %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 1px 0 0 1px;
    }
</style>
</head>
  <form method="post" novalidate>
    {% csrf_token %}
    <title>Login Page</title>
      <h3>Login Here</h3>

  <div class="container">
    <input type="text" placeholder="Enter Username" name="username" required>

    <br>
    <br>

    <input type="password" placeholder="Enter Password" name="password" required>

    <br>
    <br>

    <button type="submit">Login</button>
    <br>
    <label>
      <br>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>
  <br>
  <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
  <a href="{% url 'password_reset' %}" class="btn btn-info">Forgot Password</a><br><br>
  <a href="{% url 'formapp:info' %}" class="btn btn-info">New User!!! REGISTER HERE</a>


</form>

formapp/templates/formapp/pdf.html
{% load static %}
{% load staticfiles %}


<div class="card bg-light text-dark col-sm-5">
<div class="container" enctype="multipart/form-data">
    <h1>Profile</h1>
    <img class="rounded-circle account-img" img src="{{ employee.Image.url }}" width="200">
    <h3>Welcome {{ employee.user.username }}</h3>
    <p>Email: {{ employee.user.email }}</p>
    <p>Gender: {{ employee.gender }}</p>
    <p>Address: {{ employee.Address }}</p>
    <p>Country: {{ employee.Country }}</p>
    <p>Programming_Languages: {{ employee.Programming_Languages}}</p>
    <p>Date_of_Birth: {{ employee.Date_of_Birth}}</p>
    <p>Mobile_No.: {{ employee.Mobile_No}}</p>
</div>

formapp/templates/formapp/register.html
{% load widget_tweaks %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 2px 0 0 2px;
    }
</style>

</head>

<form method="POST" class="post-form" enctype="multipart/form-data" novalidate>
  {% csrf_token %}
  <div class="container">
    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Enter Details</h3>
        </div>
    </div>

  {% for field in form %}
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
      <div class="col-sm-4">
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
            {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
      {% endif %}
      </div>
    </div>
  {% endfor %}

  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
      <button type="submit" class="btn btn-primary">Submit</button>
      <a href="{% url 'formapp:login' %}" class="btn btn-info">Existing User!!! Login</a>
      </div>
    </div>
  </div>
</form>

formapp/templates/formapp/settings.html
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 1px 0 0 1px;
    }
</style>
</head>

    {% if user.is_authenticated %}
    <h3 class="text-center">  You are signed in as <strong>{{ user.username }}</strong> </h3>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <ul class="nav navbar-nav">

            <li><a href="{% url 'logout' %}">logout</a></li>
            <li><a href="{% url 'formapp:update' employee.user_id %}">Add more info</a></li>
          </ul>
        </div>
      </nav>
{% endif %}


  <h2>Settings</h2>


  <h3>GitHub</h3>
  {% if github_login %}
    <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">{{ github_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'github' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from GitHub</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from GitHub</button>
      <p style="color: red">You must     <a href="{% url 'formapp:change_password' employee.user_id  %}" class="btn btn-info">Change Password</a></p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
  {% endif %}

formapp/templates/formapp/show.html
{% load widget_tweaks %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 1px 0 0 1px;
    }
</style>
</head>

<!-- <br>
<div class="row">
    <div class="col-6"></div>
      <div class="col-6">
      <input class="form-control border-secondary py-2" id="myInput" type="text" placeholder="Search..">
    </div>
</div> -->
<br>

  <table class="table table-bordered table-sm">
    <!-- table-striped -->
      <thead class="thead-dark">
        <tr>
            <th>Employee Name</th>
            <th>Employee Email</th>
            <th>Employee Contact</th>
            <th>Employee BirthDate</th>
            <th>Gender</th>
            <th>Address</th>
            <th>Upload File</th>
            <th>Actions</th>
            </tr>
        </thead>
        <tbody id="myTable">
          {% for employee in employees %}
          <tr>
            <td>{{ employee.user.username }}</td>
            <td>{{ employee.user.email }}</td>
            <td>{{ employee.Mobile_No }}</td>
            <td>{{ employee.Date_of_Birth }}</td>
            <td>{{ employee.gender }}</td>
            <td>{{ employee.Address }}</td>
            <td>{{ employee.Image }}</td>
            <td>
            <a href="{% url 'formapp:html_to_pdf_view' id=employee.user_id %}" class="btn btn-info">Print</a>
            <a href="{% url 'formapp:employee_delete' id=employee.user_id %}"  class="btn btn-info"  style="background-color:#f44336">Delete</a>
            <a href="{% url 'formapp:update' id=employee.user_id %}" class="btn btn-info" style="background-color:Orange">Edit</a>
            <a href="{% url 'formapp:view_profile' id=employee.user_id %}" class="btn btn-info" style="background-color:MediumSeaGreen">View</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>


<!-- if we had hundreds or thousands of posts then loading them all at once, could take a while.
Implementing pagination not only makes the site load faster, but it is also great in terms of usability.
Django provides a class named Paginator which allows us to create paginated records.
 To use it, import it from django.core.paginator module. -->
 <center><a href="{% url 'logout' %}?next=/employee/" class="btn btn-info">Logout</a></center>


{% if employees.has_other_pages %}
<ul class="pagination">
  {% if employees.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ employees.previous_page_number }}">&laquo</a></li>
  {% else %}
  <li class="disabled"><span></span></li>
  {% endif %}
  {% for i in employees.paginator.page_range %}
  {% if employees.number == i%}
  <li class="page-item"><span class="btn btn-primary">{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if employees.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ employees.next_page_number }}">&laquo</a></li>
  {% else %}
  <li class="disabled"><span></span></li>
  {% endif %}
</ul>
{% endif %}

<!-- <script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script> -->

formapp/templates/formapp/update.html
{% load widget_tweaks %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }
    input[type=radio], input.radio {
      margin: 2px 0 0 2px;
    }
</style>

</head>

<form method="POST" class="post-form" enctype="multipart/form-data" novalidate>
  {% csrf_token %}
  <div class="container">
    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Enter Details</h3>
        </div>
    </div>

  {% for field in form %}
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
      <div class="col-sm-4">
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
            {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
      {% endif %}
      </div>
    </div>
  {% endfor %}

  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
      <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </div>
</form>